name: Release
on:
  push:
    branches: [main]
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.7.9
        id: release
        with:
          release-type: simple
          package-name: nm-fzf
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
          extra-files: |
            nm-fzf
            .github/ISSUE_TEMPLATE/bug.yml
          plugins: sentence-case
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          fetch-depth: 0
          fetch-tags: true
      - name: tag stable versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git tag -d stable || true
          git push origin :stable || true
          git tag -a stable -m "Last Stable Release"
          git push origin stable
